log_path: "logs/rebuild.log"
cluster: shard_cluster
shard:
  shard1:
    host1:
      hostname: localhost:27200
      ip: 3440f75127c6
      server_hardware_configuration: MEDIUM
      storage_path: /data/db
      service_name: mongod
      credentials:
        username: admin
        password: admin
    host2:
      hostname: localhost:27201
      ip: 2405b2d9c05b
      server_hardware_configuration: MEDIUM
      storage_path: /data/db
      service_name: mongod
      credentials:
        username: admin
        password: admin
    host3:
      hostname: localhost:27202
      ip: 6b07da70e43b
      server_hardware_configuration: MEDIUM
      storage_path: /data/db
      service_name: mongod
      credentials:
        username: admin
        password: admin

  shard2:
    host1:
      hostname: localhost:27300
      ip: 7385c86e52eb
      server_hardware_configuration: HIGH
      storage_path: /data/db
      service_name: mongod
      credentials:
        username: admin
        password: admin
    host2:
      hostname: localhost:27301
      ip: 358c51281170
      server_hardware_configuration: HIGH
      storage_path: /data/db
      service_name: mongod
      credentials:
        username: admin
        password: admin
    host3:
      hostname: localhost:27302
      ip: 5928790a2038
      server_hardware_configuration: HIGH
      storage_path: /data/db
      service_name: mongod
      credentials:
        username: admin
        password: admin

config_servers:
  host1:
    hostname: localhost:27100
    ip: 127.0.0.1
    server_hardware_configuration: LOW
    storage_path: /data/db
    service_name: mongod
    credentials:
      username: admin
      password: admin
  host2:
    hostname: localhost:27101
    ip: 127.0.0.1
    server_hardware_configuration: LOW
    storage_path: /data/db
    service_name: mongod
    credentials:
      username: admin
      password: admin
  host3:
    hostname: localhost:27102
    ip: 127.0.0.1
    server_hardware_configuration: LOW
    storage_path: /data/db
    service_name: mongod
    credentials:
      username: admin
      password: admin
